url: https://phpwebdevelope.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Caribbean Fashion House
email: your-email@domain.com
description: "Jamaican Fashion Couture House for womenswear."


# Team names, titles and social links
people:
- name: M. M. Fennel
  pic: 1
  position: Creative Director
  social:
    - title: twitter
      url: https://www.twitter.com/houseoffennel
    - title: facebook
      url:  https://www.facebook.com/houseoffennel
    - title: instagram
      url: https://www.instagram.com/houseoffennel

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/houseoffennel
  - title: facebook
    url: https://www.facebook.com/houseoffennel
  - title: instagram
    url: https://www.instagram.com/houseoffennel
  - title: google plus 
    url: http://plus.google.com/houseoffennel

# Postal address (add as many lines as necessary)
address:
  - line: Portmore
  - line: Jamaica
  - line: West Indies

# Build settings
markdown: kramdown
permalink: pretty
