# basic options
title: The Fashion House
author: Courtuier
email: your-email@domain.com
description: The place for High Fashion
twitter_username: jekyllrb

# Build settings
markdown: kramdown
theme: jekyll-theme-instagram-portfolio

# File: _config.yml
layout: pages
webrick:
  headers:
    My-Header: My-Value
    My-Other-Header: My-Other-Value
    
